monitor.alsa.rules = [
  # ── RODECaster Duo ─────────────────────────────────────────────
  {
    matches = [
      {
        device.name = "~alsa_card.usb-R__DE_RODECaster_Duo_.*"
      }
    ]
    actions = {
      update-props = {
        "device.description": "RODECaster Duo",
        "device.nick": "RODECaster Duo",
        "device.profile": "pro-audio"
      }
    }
  },
  {
    matches = [
      {
        device.name = "~alsa_card.usb-R__DE_R__DECaster_Duo.*"
      }
    ]
    actions = {
      update-props = {
        "device.description": "RODECaster Duo Secondary",
        "device.nick": "RODECaster Secondary",
        "device.profile": "pro-audio"
      }
    }
  },
  {
    matches = [
      {
        node.name = "~alsa_.*.usb-R__DE_RODECaster_Duo_.*.pro-.*-0"
      }
    ]
    actions = {
      update-props = {
        "node.description": "RODECaster Duo Chat",
        "node.nick": "RODECaster Chat"
      }
    }
  },
  {
    matches = [
      {
        node.name = "~alsa_.*.usb-R__DE_RODECaster_Duo_.*.pro-.*-1"
      }
    ]
    actions = {
      update-props = {
        "node.description": "RODECaster Duo Main",
        "node.nick": "RODECaster Main"
      }
    }
  },
  # ── RODECaster Pro II ──────────────────────────────────────────
  {
    matches = [
      {
        device.name = "~alsa_card.usb-R__DE_RODECaster_Pro_II_.*"
      }
    ]
    actions = {
      update-props = {
        "device.description": "RODECaster Pro II",
        "device.nick": "RODECaster Pro II",
        "device.profile": "pro-audio"
      }
    }
  },
  {
    matches = [
      {
        device.name = "~alsa_card.usb-R__DE_R__DECaster_Pro_II.*"
      }
    ]
    actions = {
      update-props = {
        "device.description": "RODECaster Pro II Secondary",
        "device.nick": "RODECaster Pro II Secondary",
        "device.profile": "pro-audio"
      }
    }
  },
  {
    matches = [
      {
        node.name = "~alsa_.*.usb-R__DE_RODECaster_Pro_II_.*.pro-.*-0"
      }
    ]
    actions = {
      update-props = {
        "node.description": "RODECaster Pro II Chat",
        "node.nick": "RODECaster Pro II Chat"
      }
    }
  },
  {
    matches = [
      {
        node.name = "~alsa_.*.usb-R__DE_RODECaster_Pro_II_.*.pro-.*-1"
      }
    ]
    actions = {
      update-props = {
        "node.description": "RODECaster Pro II Main",
        "node.nick": "RODECaster Pro II Main"
      }
    }
  }
]
